Repository swyg-goorm/client, pull requests merged in 2023-03, with the labels that each got.

#45 feat: 둘러보기 페이지 개발
  next.config.js
  src/components/common/Button.tsx
  src/components/common/layout.tsx
  src/pages/_app.tsx
  src/pages/api/hobbies.ts
  src/pages/browsing.tsx
  src/pages/index.tsx
  src/pages/question.tsx
  src/types/hobby.ts
Labels: ✨ Feature

#58 fix: question페이지 버그 해결
  src/pages/question.tsx
  src/types/getUserQuestion.ts
Labels: 🐞 Bug

#60 feat:질문 완료시 로딩페이지로 이동
  src/pages/_app.tsx
  src/pages/loading.tsx
  src/pages/question.tsx
  src/store/atom.ts
Labels: ✨ Feature, 🔨 Refactor

#68 fix: 잠금해제 범위 안벗어나도록
  src/pages/index.tsx
Labels: 🐞 Bug

#64 feat: 로딩창 닉네임 적용 반응형 리팩토링
  src/api/getUserQuestion.ts
  src/pages/begin.tsx
  src/pages/question.tsx
  src/styles/globals.css
Labels: 🐞 Bug, 🔨 Refactor

#66 fix: 문제 12번에서 클릭시 13번 보임
  src/pages/question.tsx
Labels: 🐞 Bug

#69 fix: 메인페이지 오타 수정 데이터 반영
  src/api/getUserCount.ts
  src/pages/index.tsx
  src/types/getUserCount.ts
Labels: 🐞 Bug

#71 QA 반영 리팩토링
  public/static/test_result_logo.svg
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/Loader.tsx
  src/components/common/Modal.tsx
  src/components/common/ProgressBar.tsx
  src/components/common/Top20List.tsx
  src/components/common/TopBar.tsx
  src/components/common/layout.tsx
  src/components/result/Card.tsx
  src/components/result/FitHobby.tsx
  src/components/result/KakaoShare.tsx
  src/components/result/Lights.tsx
  src/components/result/Model.tsx
  src/components/result/Share.tsx
  src/pages/_app.tsx
  src/pages/begin.tsx
  src/pages/browsing.tsx
  src/pages/index.tsx
  src/pages/loading.tsx
  src/pages/question.tsx
  src/pages/result.tsx
Labels: 🐞 Bug, ✨ Feature, 🔨 Refactor

#73 feat: QA 리팩토링
  src/components/common/Button.tsx
  src/components/common/TopBar.tsx
  src/components/common/layout.tsx
  src/pages/begin.tsx
  src/pages/index.tsx
  src/pages/question.tsx
Labels: 🐞 Bug, 🔨 Refactor

#76 QA - 결과 페이지 분리
  src/components/common/Button.tsx
  src/components/result/Card.tsx
  src/components/result/FitHobby.tsx
  src/components/result/KakaoShare.tsx
  src/components/result/Share.tsx
  src/pages/result.tsx
Labels: ✨ Feature

#80 refactor: 둘러보기 페이지 리팩토링
  src/components/common/Top20List.tsx
  src/components/common/layout.tsx
  src/pages/browsing.tsx
Labels: 🔨 Refactor

#79 QA - 로딩 화면 png파일 + css로 구현 & 반응형으로 구현 & 취미 API 사용
  public/static/gif 이미지 (16가지).png
  public/static/gif 이미지 (5가지).png
  src/components/common/Loader.tsx
  src/components/result/Share.tsx
  src/pages/loading.tsx
  src/pages/result.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: 🐞 Bug

#82 feat: layout style, begin페이지 스타일 수정
  src/components/common/layout.tsx
  src/pages/begin.tsx
Labels: 🐞 Bug, ✨ Feature

#87 QA 수정사항 반영
  src/components/common/Button.tsx
  src/components/result/FitHobby.tsx
  src/components/result/HobbyDetail.tsx
  src/pages/_app.tsx
  src/pages/begin.tsx
  src/pages/question.tsx
  src/pages/result.tsx
Labels: 🐞 Bug, ✨ Feature, 🔨 Refactor

#90 refactor: QA사항 반영
  src/api/hobbies.ts
  src/components/result/HobbyDetail.tsx
  src/pages/browsing.tsx
  src/pages/index.tsx
  src/pages/question.tsx
  src/styles/globals.css
Labels: 🐞 Bug, 🔨 Refactor

#93 refactor: 이미지 로드시 화면 보여주도록
  src/pages/question.tsx
Labels: 🔨 Refactor

#97 feat,fix: QA 리팩토링
  public/static/left_background.svg
  public/static/right_background.svg
  src/components/common/Button.tsx
  src/components/common/layout.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/question.tsx
  tailwind.config.js
Labels: 🐞 Bug, ✨ Feature

#100 fix: 뒤로가기 정책 반영
  src/pages/begin.tsx
  src/pages/browsing.tsx
  src/pages/question.tsx
  src/pages/result.tsx
Labels: 🐞 Bug

#101 fix: 로딩중 컴포넌트로 변경
  src/pages/question.tsx
Labels: 🐞 Bug

#104 fix: 프론트엔드 QA
  src/pages/index.tsx
  src/pages/question.tsx
Labels: 🐞 Bug

#107 fix: QA 리팩토링
  src/components/common/Button.tsx
  src/components/result/Share.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/question.tsx
  src/pages/result.tsx
  src/styles/globals.css
  src/utils/shareKaKaoLink.ts
Labels: 🐞 Bug, ✨ Feature, 🔨 Refactor

#112 중복 코드 제거
  src/pages/begin.tsx
  src/pages/index.tsx
Labels: 🐞 Bug

#115 style: 디자인 검수 반영
  src/components/common/Button.tsx
  src/components/result/HobbyDetail.tsx
  src/components/result/Share.tsx
  src/pages/index.tsx
  src/pages/question.tsx
  src/pages/result.tsx
Labels: 🧑‍🎨 Style

#123 style,refactor: 디자인 검수 코드 리팩토링
  src/components/common/Button.tsx
  src/components/common/Top20List.tsx
  src/pages/_app.tsx
  src/pages/begin.tsx
  src/pages/browsing.tsx
  src/pages/question.tsx
  src/pages/result.tsx
  src/styles/globals.css
Labels: 🐞 Bug, 🔨 Refactor, 🧑‍🎨 Style

#127 fix: 디자인 반영
  src/components/common/Button.tsx
  src/components/common/layout.tsx
  src/pages/result.tsx
  src/styles/globals.css
Labels: 🐞 Bug

#126 QA 수정사항 반영
  public/static/logo_main.png
  src/components/common/TopBar.tsx
  src/components/common/layout.tsx
Labels: 🔨 Refactor

#130 fix,refactor: 최종 2차 QA 리팩토링
  src/components/common/Button.tsx
  src/components/result/Card.tsx
  src/components/result/FitHobby.tsx
  src/components/result/Model.tsx
  src/pages/begin.tsx
  src/pages/browsing.tsx
  src/pages/result.tsx
Labels: 🐞 Bug, 🔨 Refactor

#134 프로젝트 3차 QA 리팩토링
  robots.txt
  src/components/MetaHead.tsx
  src/pages/_app.tsx
Labels: 🐞 Bug, 🔨 Refactor

#140 fix:구글 애즈 반영
  src/components/common/GoogleAd.tsx
Labels: 🐞 Bug

#143 fix : 디자인 수정 사항 반영
  src/components/common/Button.tsx
  src/components/result/Card.tsx
  src/components/result/HobbyDetail.tsx
  src/pages/result.tsx
Labels: 🧑‍🎨 Style

#147 fix: 구글 애즈 반영
  src/components/MetaHead.tsx
  src/components/common/Button.tsx
  src/components/common/GoogleAd.tsx
  src/components/common/ResultLoader.tsx
  src/components/common/Top20List.tsx
  src/components/result/Card.tsx
  src/components/result/FitHobby.tsx
  src/components/result/HobbyDetail.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: 🐞 Bug

#148 delivery: 구글 애즈 버그 픽스
  src/components/MetaHead.tsx
  src/components/common/Button.tsx
  src/components/common/GoogleAd.tsx
  src/components/common/ResultLoader.tsx
  src/components/common/Top20List.tsx
  src/components/result/Card.tsx
  src/components/result/FitHobby.tsx
  src/components/result/HobbyDetail.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: 🎁 Delivery

#151 fix: 구글 애즈 버그
  src/components/MetaHead.tsx
  src/components/common/GoogleAd.tsx
  src/components/common/ResultLoader.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: 🐞 Bug
