Repository swyg-goorm/client, pull requests merged in 2023-02, with the labels that each got.

#9 <Head> - favicon, title 추가
  public/static/favicon.ico
  src/pages/_app.tsx
  tsconfig.json
Labels: ✨ Feature

#10 [FE-3]feat: tailwindConfig, globalcss설정
  src/styles/globals.css
  tailwind.config.js
Labels: ✨ Feature

#14 [FE-4] 공통 컴포넌트 - Input 구현
  src/components/common/Input.tsx
Labels: ✨ Feature

#15 feat : PrgressBar 컴포넌트 구현
  src/components/common/ProgressBar.tsx
  src/pages/index.tsx
  tailwind.config.js
Labels: ✨ Feature

#21 chore : 색깔 재정의, 컴포넌트에 적용
  src/components/common/ProgressBar.tsx
  src/components/common/Top20List.tsx
  src/components/common/layout.tsx
  tailwind.config.js
Labels: 🎸chore

#23 ProgressBar 스타일 수정
  src/components/common/ProgressBar.tsx
Labels: 🐞 Bug

#25 feat: 버튼 컴포넌트 생성
  src/components/common/Button.tsx
Labels: ✨ Feature

#33 feat: 메인페이지 작업 임시저장
  public/static/main_character.svg
  src/components/common/layout.tsx
  src/pages/_app.tsx
  src/pages/api/getUserCount.ts
  src/pages/api/instance.ts
  src/pages/index.tsx
Labels: ✨ Feature

#27 유저명 입력 페이지 구현
  .yarn/cache/tailwind-scrollbar-hide-npm-1.1.7-537baa5b75-2434a1db7a.zip
  package.json
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/Modal.tsx
  src/components/common/TopBar.tsx
  src/components/common/layout.tsx
  src/pages/begin.tsx
  src/styles/globals.css
  tailwind.config.js
  yarn.lock
Labels: ✨ Feature

#39 feat: 메인 페이지 구현
  src/pages/browsing.tsx
  src/pages/index.tsx
Labels: ✨ Feature

#41 feat: 질문 페이지 구현
  next.config.js
  src/pages/api/getUserQuestion.ts
  src/pages/question.tsx
  src/types/getUserQuestion.ts
Labels: ✨ Feature

#46 fix: 슬라이더 클릭시 페이지 이동하도록
  src/pages/index.tsx
Labels: ✨ Feature
